# Use the official Node.js base image with version 14 as the builder stage
FROM node:14 as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application to the working directory
COPY . .

# Build the Angular application
RUN npm run build --prod

# Use the official Nginx base image for the final stage
FROM nginx:latest

# Copy custom configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the built Angular app to the Nginx public directory
COPY --from=builder /app/dist/* /usr/share/nginx/html/

# Expose the default Nginx port
EXPOSE 80

# Start Nginx when the container is run
CMD ["nginx", "-g", "daemon off;"]
